server:
  port: 8082

spring:
  application:
    name: course-service
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.31.8:8848
        group: AI_LEARNING_PLATFORM_GROUP
      config:
        server-addr: 123.57.31.8:8848
        file-extension: yml
        group: DEFAULT_GROUP

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  config:
    import:
      - optional:nacos:application-mysql.yml
      - optional:nacos:application-redis.yml
      - optional:nacos:application-rabbitmq.yml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    password: xuanyuan-secret
