server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.31.8:8848
        group: AI_LEARNING_PLATFORM_GROUP
      config:
        server-addr: 123.57.31.8:8848
        file-extension: yml
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: auth-service-direct
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: course-service-api
          uri: lb://course-service
          predicates:
            - Path=/course/**,/chapter/**,/resource/**
        - id: course-service-direct
          uri: lb://course-service
          predicates:
            - Path=/course-service/**
          filters:
            - StripPrefix=1
        - id: upload-service-websocket
          uri: lb:ws://upload-service
          predicates:
            - Path=/upload/ws/**
        - id: upload-service-api
          uri: lb://upload-service
          predicates:
            - Path=/upload/**
        - id: upload-service-direct
          uri: lb://upload-service
          predicates:
            - Path=/upload-service/**
          filters:
            - StripPrefix=1
  config:
    import:
      - optional:nacos:application-redis.yml

auth:
  whitelist:
    urls:
      - /auth/login
      - /auth/register
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /favicon.ico
      - /auth-service/v3/api-docs
      - /course-service/v3/api-docs
      - /upload-service/v3/api-docs
      - /*/v3/api-docs/**

knife4j:
  enable: true
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: 认证服务
        url: /auth-service/v3/api-docs
        service-name: auth-service
        order: 1
      - name: 课程服务
        url: /course-service/v3/api-docs
        service-name: course-service
        order: 2
      - name: upload-service
        url: /upload-service/v3/api-docs
        service-name: upload-service
        order: 3

jasypt:
  encryptor:
    password: xuanyuan-secret
