server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import:
      - optional:nacos:application-mysql.yml
      - optional:nacos:application-redis.yml
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.31.8:8848
        group: AI_LEARNING_PLATFORM_GROUP
      config:
        server-addr: 123.57.31.8:8848
        file-extension: yml
        group: DEFAULT_GROUP

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

jasypt:
  encryptor:
    password: xuanyuan-secret
