spring:
  application:
    name: online-learning-parent
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.31.8:8848
      config:
        server-addr: 123.57.31.8:8848
        file-extension: yml
        shared-configs:
          - data-id: application-mysql.yml
            refresh: true
          - data-id: application-redis.yml
            refresh: true
          - data-id: application-rabbitmq.yml
            refresh: true

jasypt:
  encryptor:
    password: xuanyuan-secret
