spring:
  rabbitmq:
    host: ${RABBIT_HOST:123.57.31.8}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PWD:ENC(guest)}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
